service: keywords
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    MONGO_CONNECTION_STRING: ${ssm:/primary_db_connection_string}

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: "api.${ssm:/primary_domain_name}"
    certificateArn: ${ssm:/primary_domain_cert_arn}
    basePath: "keywords"
    createRoute53Record: true
    createRoute53IPv6Record: true
    endpointType: "regional"
    securityPolicy: tls_1_2
    apiType: rest
    autoDomain: true

functions:
  addKeyword:
    timeout: 30
    handler: index.add_keyword
    logRetentionInDays: 30
    events:
      - http:
          path: /
          method: post
          cors: 
            origin: '*'
            headers: '*'

  getKeywords:
    timeout: 30
    handler: index.get_keywords
    logRetentionInDays: 30
    events:
      - http:
          path: /
          method: get
          cors: 
            origin: '*'
            headers: '*'

  getKeywordById:
    timeout: 30
    handler: index.get_keyword_by_id
    logRetentionInDays: 30
    events:
      - http:
          path: /{keyword_id}
          method: get
          request:
            parameters:
              paths:
                keyword_id: true
          cors: 
            origin: '*'
            headers: '*'

  updateKeyword:
    timeout: 30
    handler: index.update_keyword
    logRetentionInDays: 30
    events:
      - http:
          path: /{keyword_id}
          method: post
          request:
            parameters:
              paths:
                keyword_id: true
          cors: 
            origin: '*'
            headers: '*'

  deleteKeyword:
    timeout: 30
    handler: index.delete_keyword
    logRetentionInDays: 30
    events:
      - http:
          path: /{keyword_id}
          method: delete
          request:
            parameters:
              paths:
                keyword_id: true
          cors: 
            origin: '*'
            headers: '*'
