service: projects
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    MONGO_CONNECTION_STRING: ${ssm:/primary_db_connection_string}

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: "api.${ssm:/primary_domain_name}"
    certificateArn: ${ssm:/primary_domain_cert_arn}
    basePath: "projects"
    createRoute53Record: true
    createRoute53IPv6Record: true
    endpointType: "regional"
    securityPolicy: tls_1_2
    apiType: rest
    autoDomain: true

functions:
  addProject:
    timeout: 30
    handler: index.add_project
    logRetentionInDays: 30
    events:
      - http:
          path: /
          method: post
          cors: 
            origin: '*'
            headers: '*'

  getProjects:
    timeout: 30
    handler: index.get_projects
    logRetentionInDays: 30
    events:
      - http:
          path: /
          method: get
          cors: 
            origin: '*'
            headers: '*'

  getProjectById:
    timeout: 30
    handler: index.get_project_by_id
    logRetentionInDays: 30
    events:
      - http:
          path: /{project_id}
          method: get
          request:
            parameters:
              paths:
                project_id: true
          cors: 
            origin: '*'
            headers: '*'

  updateProject:
    timeout: 30
    handler: index.update_project
    logRetentionInDays: 30
    events:
      - http:
          path: /{project_id}
          method: post
          request:
            parameters:
              paths:
                project_id: true
          cors: 
            origin: '*'
            headers: '*'

  deleteProject:
    timeout: 30
    handler: index.delete_project
    logRetentionInDays: 30
    events:
      - http:
          path: /{project_id}
          method: delete
          request:
            parameters:
              paths:
                project_id: true
          cors: 
            origin: '*'
            headers: '*'
