service: search-terms
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    MONGO_CONNECTION_STRING: ${ssm:/primary_db_connection_string}

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: "api.${ssm:/primary_domain_name}"
    certificateArn: ${ssm:/primary_domain_cert_arn}
    basePath: "searchTerms"
    createRoute53Record: true
    createRoute53IPv6Record: true
    endpointType: "regional"
    securityPolicy: tls_1_2
    apiType: rest
    autoDomain: true

functions:
  addSearchTerm:
    timeout: 30
    handler: index.add_searchTerm
    logRetentionInDays: 30
    events:
      - http:
          path: /
          method: post
          cors: 
            origin: '*'
            headers: '*'

  getSearchTerms:
    timeout: 30
    handler: index.get_searchTerms
    logRetentionInDays: 30
    events:
      - http:
          path: /
          method: get
          cors: 
            origin: '*'
            headers: '*'

  getSearchTermById:
    timeout: 30
    handler: index.get_searchTerm_by_id
    logRetentionInDays: 30
    events:
      - http:
          path: /{searchTerm_id}
          method: get
          request:
            parameters:
              paths:
                searchTerm_id: true
          cors: 
            origin: '*'
            headers: '*'

  updateSearchTerm:
    timeout: 30
    handler: index.update_searchTerm
    logRetentionInDays: 30
    events:
      - http:
          path: /{searchTerm_id}
          method: post
          request:
            parameters:
              paths:
                searchTerm_id: true
          cors: 
            origin: '*'
            headers: '*'

  deleteSearchTerm:
    timeout: 30
    handler: index.delete_searchTerm
    logRetentionInDays: 30
    events:
      - http:
          path: /{searchTerm_id}
          method: delete
          request:
            parameters:
              paths:
                searchTerm_id: true
          cors: 
            origin: '*'
            headers: '*'
