service: lambdaedge-poc
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  memorySize: 128
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource:
            - "arn:aws:logs:*:*:log-group:*:*"

plugins:
  - serverless-python-requirements
  - serverless-lambda-edge-pre-existing-cloudfront

custom:
  cloud_dist: "E10SXSB5UHXETJ"
  pythonRequirements:
    dockerizePip: non-linux
    useStaticCache: false

package:
  individually: true
  exclude:
    - ./**
  include:
    - "!./**"

functions:
  EdgeViewer:
    handler: handler.edge_viewer
    module: src
    vendor: ../../lib/python
    package:
      include:
        - src/**
    timeout: 5
    events:
      - preExistingCloudFront:
          distributionId: ${self:custom.cloud_dist}
          eventType: viewer-request
          pathPattern: "*"
          includeBody: false

  EdgeOrigin:
    handler: handler.edge_origin
    module: src
    vendor: ../../lib/python
    package:
      include:
        - src/**
    timeout: 5
    events:
      - preExistingCloudFront:
          distributionId: ${self:custom.cloud_dist}
          eventType: origin-request
          pathPattern: "*"
          includeBody: false

resources:
  Resources:
    IamRoleLambdaExecution:
      Type: "AWS::IAM::Role"
      Properties:
        AssumeRolePolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
                  - edgelambda.amazonaws.com