service: ai
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    MONGO_CONNECTION_STRING: ${ssm:/primary_db_connection_string}
    OPENAI_API_KEY: ${ssm:/openai_secret_key}
plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: "api.${ssm:/primary_domain_name}"
    certificateArn: ${ssm:/primary_domain_cert_arn}
    basePath: "ai"
    createRoute53Record: true
    createRoute53IPv6Record: true
    endpointType: "regional"
    securityPolicy: tls_1_2
    apiType: rest
    autoDomain: true

functions:
  generateKeywords:
    timeout: 30
    handler: index.generate_keywords
    logRetentionInDays: 30
    events:
      - http:
          method: post
          path: /generate_keywords
          cors:
            origin: "*"
            headers: "*"
  generateProjectTitle:
    timeout: 30
    handler: index.generate_project_title
    logRetentionInDays: 30
    events:
      - http:
          method: post
          path: /generate_project_title
          cors:
            origin: "*"
            headers: "*"
  generateSearchTerms:
    timeout: 30
    handler: index.generate_search_terms
    logRetentionInDays: 30
    events:
      - http:
          method: post
          path: /generate_search_terms
          cors:
            origin: "*"
            headers: "*"
  generateContentTeasers:
    timeout: 30
    handler: index.generate_content_teasers
    logRetentionInDays: 30
    events:
      - http:
          method: post
          path: /generate_content_teasers
          cors:
            origin: "*"
            headers: "*"
  generateContentOutline:
    timeout: 30
    handler: index.generate_content_outline
    logRetentionInDays: 30
    events:
      - http:
          method: post
          path: /generate_content_outline
          cors:
            origin: "*"
            headers: "*"
